name: datum
description:  A powerful, offline-first data synchronization engine for Flutter and Dart, featuring relational data support, real-time queries, and intelligent conflict resolution.

version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  rxdart: ^0.28.0
  equatable: ^2.0.5
  uuid: ^4.4.0
  collection: ^1.19.1
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  fake_async: ^1.3.1
  mocktail: ^1.0.4
  test: ^1.25.2
