name: datum
description:  A powerful, offline-first data synchronization engine for Flutter and Dart, featuring relational data support, real-time queries, and intelligent conflict resolution.
version: 0.0.6
homepage: https://www.shreeman.dev
repository: https://github.com/Shreemanarjun/datum
issue_tracker: https://github.com/Shreemanarjun/datum/issues
documentation: https://datum.shreeman.dev/
funding:
 - https://buymeacoffee.com/shreemanarjun
screenshots:
  - description: 'LOGO Datum'
    path: logo/datum.png

topics:
  - offline-first
  - synchronization
  - database
  - flutter
  - supabase

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  equatable: ^2.0.5
  rxdart: ^0.28.0
  uuid: ^4.4.0
  collection: ^1.19.1
  meta: ^1.16.0

dev_dependencies:
  lints: ^4.0.0
  fake_async: ^1.3.1
  mocktail: ^1.0.4
  test: ^1.25.2
