name: datum_ecosystem
publish_to: none
environment:
  sdk: ^3.6.0


workspace:
  - packages/datum
  - packages/datum_docs
  - packages/datum_generator
  - packages/datum_sqlite
  - packages/datum_test


