name: datum_generator
description: Code generator for the Datum framework.
version: 1.1.0
resolution: workspace
homepage: https://www.shreeman.dev
repository: https://github.com/Shreemanarjun/datum
issue_tracker: https://github.com/Shreemanarjun/datum/issues
documentation: https://datum.shreeman.dev/
funding:
  - https://buymeacoffee.com/shreemanarjun

screenshots:
  - description: 'LOGO Datum'
    path: logo/datum.webp

topics:
  - offline-first
  - synchronization
  - database
  - flutter
  - supabase
environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  analyzer: '>=7.0.0 <9.0.0'
  build: ">=3.0.0 <5.0.0"
  source_gen: ">=3.0.0 <5.0.0"
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.10.3
  build_test: ^3.5.3
  lints: ^4.0.0
  test: ^1.25.6
